### ISSUE TITLE
'failed to initialize container' when starting a task under Vagrant VM

### ISSUE THREAD

**Issue by camelpunch** [cloudfoundry-incubator/receptor#10]
Hi folks,

I'm getting to grips with using the receptor API for the purpose of creating tasks. I've got as far as persuading it to download a rootfs docker image by POSTing to /tasks. I am pretty sure it's downloading the image properly as I see high incoming network traffic for the VM, and it drops out when the "state" switches to "COMPLETED".

However, the failure_message in the status I retrieve with a GET is always "failed to initialize container". I can't find this string in the source of either lattice or receptor (guessing it's diego itself), and have no familiarity with the codebase. 

I can push normal apps to this instance, using ltc.

What's a good way to debug what I'm doing?

Here's the POST /tasks request body:

```json
{"domain":"foo",
  "task_guid":"mygreattask103",
  "stack":"lucid64",
  "privileged":false,
  "rootfs":"docker:///cloudfoundry/lucid64",
  "action":{
    "run":{"args":["hello-world"],"path":"/bin/echo"}
  },
  "disk_mb":100,
  "memory_mb":1000}
```

And the response I get back from GET /tasks:

```json
[{"action":{"run":{"path":"/bin/echo","args":["hello-world"],"env":null,"resource_limits":{}}},"completion_callback_url":"","cpu_weight":0,"disk_mb":100,"domain":"foo","log_guid":"","log_source":"","metrics_guid":"","memory_mb":1000,"result_file":"","stack":"lucid64","task_guid":"mygreattask103","rootfs":"docker:///cloudfoundry/lucid64","privileged":false,"cell_id":"lattice-cell-01","created_at":1425398903244962318,"failed":true,"failure_reason":"failed to initialize container","result":"","state":"COMPLETED"}]
```

**Comment by camelpunch** [comment]
By 'normal apps' I mean LRPs such as the example dockerized app.

**Comment by ematpl** [comment]
Thanks, @camelpunch! Generated https://www.pivotaltracker.com/story/show/89520620 manually in the Diego backlog and pinged your Tracker user on it.

**Comment by camelpunch** [comment]
This is no longer happening. I think I got my machine into a weird state with an older version of Lattice. Sorry for noise!
