### ISSUE TITLE
receptor client returns empty error on 404

### ISSUE THREAD

**Issue by davidwadden** [cloudfoundry-incubator/receptor#13]
In Lattice, we come across the following issue attempting to `ltc target DOMAIN` when "receptor.DOMAIN" does not match the value passed to`-domainNames` on the receptor (Lattice uses xip.io).  Specifically, we advise users to [install dnsmasq](https://github.com/cloudfoundry-incubator/lattice/blob/master/docs/dnsmasq-readme.md) if they have troubles using **xip.io**.  

When there is a domain name mismatch, `ltc target` behaves as follows:
```
✔ ~/workspace/diego-release/src/github.com/cloudfoundry-incubator/lattice [develop|✔]
13:22 $ ltc target lattice.dev
Error verifying target:
```

We've identified https://github.com/cloudfoundry-incubator/receptor/blob/master/client.go#L237, when the receptor client attempts to unmarshal the error response when the http status code > 299, as part of the problem for us.  This leads to the empty error message above.  The receptor client is attempting to unmarshal error data into a `receptor.Error`, but the "json" it's atttempting to unmarshal is:
```
✔ ~/workspace/diego-release/src/github.com/cloudfoundry-incubator/lattice [develop|✔]
13:22 $ curl http://receptor.lattice.dev/v1/cells
404 Not Found: Requested route ('receptor.lattice.dev') does not exist.
```

We'd like to submit a pull request to change this behavior, to define a couple new errors in https://github.com/cloudfoundry-incubator/receptor/blob/master/errors.go, such as **ResourceNotFound** (when StatusCode = 404) and **CannotDecodeErrorResponse** (when unmarshaling into the errResponse fails).

Let us know if you have any feedback regarding this.
David+KL

**Comment by ematpl** [comment]
Are there any remaining issues with this after #14 was merged in?

Thanks,
Eric

**Comment by davidwadden** [comment]
No remaining issues -- thanks a lot!
