### ISSUE TITLE
Misleading example in documentation about LRP (docker urls)

### ISSUE THREAD

**Issue by kdvolder** [cloudfoundry-incubator/receptor#15]
This doc page 

https://github.com/cloudfoundry-incubator/receptor/blob/master/doc/lrps.md

gives an example of how to pass a reference to a docker image from dockerhub:

       "rootfs": "docker:///docker-org/docker-image#docker-tag"

That however threw me off. I assumed that putting 'docker-org' was some kind of 'special' trigger to indicate you want to fetch from docker-hub.

I finally figured out what I was doing wrong by digging into ltc source code where I found some unit tests that have clearer examples "docker:///jimbo/my-docker-app#latest". 

Yes, really, that format looks the same. But the particular values, i.e. 'jimbo' made it clear to me this piece was a username. Whereas 'docker-org' to me was a bit ambiguous and more prone to misinterpretation.

**Comment by ematpl** [comment]
Thanks for the feedback, @kdvolder. Would it be clearer if we changed 'docker-org' to 'docker-user' in that example?

Best,
Eric

**Comment by kdvolder** [comment]
I think so, yes.

**Comment by ematpl** [comment]
Fixed in https://github.com/cloudfoundry-incubator/receptor/commit/fc9af89a7ed0e274f5a9f582df9c98f51f2691e1.
