### ISSUE TITLE
Trace logging in receptor

### ISSUE THREAD

**Issue by davidwadden** [cloudfoundry-incubator/receptor#17]
First proposed by [#84349468](https://www.pivotaltracker.com/story/show/84349468) and [#84349466](https://www.pivotaltracker.com/story/show/84349466), @AmitRoushan opened cloudfoundry-incubator/lattice#132 to offer a couple implementation ideas to allow `ltc`, the Lattice CLI, to have similar functionality to **CF_TRACE** in the CF CLI.  

His implementation proposals included forking the receptor client into Lattice or having the `receptor.Client` write directly to `os.Stdout`, both of which were not preferable to us.  After a conversation with @onsi, we came up with the idea of modifying the `receptor.Client` to allow injecting a `lager.Logger` by the caller (in this case, `ltc`).

Our original idea was to simply add a `...lager.Logger` parameter to `receptor.NewClient` so that it becomes `NewClient(url string, logger ...lager.Logger) Client` -- but after speaking with @ematpl on the matter, setting the logger at construction time wouldn't give the receptor client an accurate session state when a receptor method is called.  He suggested changing each of the methods on the `Client` interface to take a (possibly optional) `lager.Logger` to remedy this.   

This issue is to start a discussion with the various teams that rely on the existing `receptor.Client` interface what would be the best implementation.

@davidwadden + @kaayell

**Comment by davidwadden** [comment]
I put together a spike (with single happy path test) that injects a logger into the `receptor.Client` at construction-time.  It doesn't take into account anything regarding the `Session` at the moment.

https://github.com/davidwadden/receptor/commit/f3e7b89c04c8bd6e4fe6bc3b54a21e9b7177fb03

The output from the tests running looks like:
```
✔ ~/workspace/diego-release/src/github.com/davidwadden/receptor [client-logger|✔]
08:43 $ ginkgo .
Running Suite: Receptor Suite
=============================
Random Seed: 1433771069
Will run 52 of 52 specs

•
==RECEPTOR REQUEST==
 {"timestamp":"1433771070.809589386","source":"test-logger","message":"test-logger.send-request","log_level":1,"data":{"request":"GET /v1/desired_lrps?domain=diego HTTP/1.1\r\nHost: 127.0.0.1:49729\r\nContent-Type: application/json\r\n\r\nnull"}}

==RECEPTOR RESPONSE==
 {"timestamp":"1433771070.809934139","source":"test-logger","message":"test-logger.receive-response","log_level":1,"data":{"response":"HTTP/1.1 200 OK\r\nContent-Length: 268\r\nContent-Type: application/json\r\nDate: Mon, 08 Jun 2015 13:44:30 GMT\r\n\r\n[{\"action\":null,\"process_guid\":\"some-guid\",\"domain\":\"diego\",\"rootfs\":\"\",\"instances\":0,\"start_timeout\":0,\"disk_mb\":0,\"memory_mb\":0,\"cpu_weight\":0,\"privileged\":false,\"ports\":null,\"log_guid\":\"\",\"log_source\":\"\",\"metrics_guid\":\"\",\"modification_tag\":{\"epoch\":\"\",\"index\":0}}]"}}
•••••••••••••••••••••••••••••••••••••••••••••••••••
Ran 52 of 52 Specs in 0.028 seconds
SUCCESS! -- 52 Passed | 0 Failed | 0 Pending | 0 Skipped PASS

Ginkgo ran 1 suite in 1.434641202s
Test Suite Passed
```

Let us know what you think
David

**Comment by ematpl** [comment]
Thanks, @davidwadden. I added https://www.pivotaltracker.com/story/show/99018428, which we discussed in Diego's IPM today and should get to pretty soon. We're happy to have discussion there about what would be best for your use of the receptor client in `ltc`.

**Comment by ematpl** [comment]
Resolved in https://www.pivotaltracker.com/story/show/99018428.
